apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: timeguild-monitor
  namespace: timeguild-monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: timeguild
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      path: /api/metrics # Endpoint exposing OpenTelemetry/Prometheus metrics in Next.js
      interval: 15s
