apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: timeguild-monitor
  namespace: timeguild-prod
  labels:
    release: prometheus-kube-stack
spec:
  selector:
    matchLabels:
      app: timeguild
      component: server
  endpoints:
    - port: http
      path: /api/metrics # Endpoint exposing OpenTelemetry/Prometheus metrics in Next.js
      interval: 15s
