replicaCount: 2

ingress:
  annotations:
    cert-manager.io/cluster-issuer: null
  hosts:
    - host: timeguild.lab
      paths:
        - path: /
          pathType: Prefix
    - host: "*.timeguild.lab"
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - timeguild.lab
        - "*.timeguild.lab"

persistence:
  storageClass: "local-path"
  size: 2Gi
