replicaCount: 2

ingress:
  annotations:
    cert-manager.io/cluster-issuer: null
  hosts:
    - host: timeguild.lab
      paths:
        - path: /
          pathType: Prefix
    - host: "*.timeguild.lab"
      paths:
        - path: /
          pathType: Prefix
  tls: null

persistence:
  type: hostPath
  hostPath: "/var/lib/timeguild/data-lab"

podSecurityContext:
  runAsNonRoot: false

networkPolicy:
  enabled: false
