apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "timeguild.fullname" . }}-config
  labels:
    {{- include "timeguild.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  PORT: "3000"
  HOSTNAME: "0.0.0.0"
  NEXT_PUBLIC_STRIPE_TEST_MODE: {{ .Values.config.NEXT_PUBLIC_STRIPE_TEST_MODE | quote }}
  SUPABASE_PROJECT_ID: {{ .Values.config.SUPABASE_PROJECT_ID | quote }}
  SUPABASE_URL: {{ .Values.config.SUPABASE_URL | quote }}
  DB_PATH: {{ .Values.config.DB_PATH | quote }}
