apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "timeguild.fullname" . }}
  labels:
    {{- include "timeguild.labels" . | nindent 4 }}
    component: server
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "timeguild.selectorLabels" . | nindent 6 }}
      component: server
  template:
    metadata:
      labels:
        {{- include "timeguild.selectorLabels" . | nindent 8 }}
        component: server
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | default (include "timeguild.fullname" .) }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nextjs
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "timeguild.fullname" . }}-config
            - secretRef:
                name: {{ include "timeguild.fullname" . }}-secrets
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: db-storage
              mountPath: {{ .Values.persistence.mountPath }}
              subPath: {{ .Values.persistence.subPath }}
          {{- end }}
          startupProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 15
          livenessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: {{ include "timeguild.fullname" . }}-db-pvc
      {{- end }}
