apiVersion: v1
kind: Secret
metadata:
  name: {{ include "timeguild.fullname" . }}-secrets
  labels:
    {{- include "timeguild.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | b64enc | quote }}
  STRIPE_SECRET_KEY: {{ .Values.secrets.STRIPE_SECRET_KEY | b64enc | quote }}
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: {{ .Values.secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY | b64enc | quote }}
  SUPABASE_PUBLISHABLE_KEY: {{ .Values.secrets.SUPABASE_PUBLISHABLE_KEY | b64enc | quote }}
  DEEPSEEK_API_KEY: {{ .Values.secrets.DEEPSEEK_API_KEY | b64enc | quote }}
