{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "timeguild.fullname" .) }}
  labels:
    {{- include "timeguild.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "timeguild.fullname" . }}-role
  labels:
    {{- include "timeguild.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "timeguild.fullname" . }}-rolebinding
  labels:
    {{- include "timeguild.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "timeguild.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | default (include "timeguild.fullname" .) }}
    namespace: {{ .Release.Namespace }}
{{- end }}
