apiVersion: v1
kind: Service
metadata:
  name: {{ include "timeguild.fullname" . }}-service
  labels:
    {{- include "timeguild.labels" . | nindent 4 }}
    component: server
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "timeguild.selectorLabels" . | nindent 4 }}
    component: server
