FROM oven/bun:1.1.34-slim
WORKDIR /app

ENV NODE_ENV=development
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Copy package requirements
COPY package.json bun.lock* ./

# Install dependencies, ignoring native compilation scripts
RUN bun install --ignore-scripts

# Copy application source
COPY . .

EXPOSE 3000

# Start Next.js hot-reloading server with Webpack
CMD ["bun", "run", "dev"]
