apiVersion: v1
kind: Namespace
metadata:
  name: timeguild-dev
  labels:
    environment: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: timeguild-staging
  labels:
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: timeguild-prod
  labels:
    environment: production
