apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: timeguild-auto-environments
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: dev
            valuesFile: values-dev.yaml
          - env: staging
            valuesFile: values-lab.yaml
  template:
    metadata:
      name: 'timeguild-{{env}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/si3mshady/time-guild-gitops.git'
        targetRevision: HEAD
        path: infra/helm/timeguild
        helm:
          valueFiles:
            - values.yaml
            - '{{valuesFile}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'timeguild-{{env}}'
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: 'timeguild-{{env}}-secrets'
          jsonPointers:
            - /data
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: timeguild-manual-environments
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - env: prod
            valuesFile: values-prod.yaml
  template:
    metadata:
      name: 'timeguild-{{env}}'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/si3mshady/time-guild-gitops.git'
        targetRevision: HEAD
        path: infra/helm/timeguild
        helm:
          valueFiles:
            - values.yaml
            - '{{valuesFile}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'timeguild-{{env}}'
      ignoreDifferences:
        - group: ""
          kind: Secret
          name: 'timeguild-{{env}}-secrets'
          jsonPointers:
            - /data
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
