loki:
  persistence:
    enabled: false

promtail:
  enabled: true
  config:
    snippets:
      extraScrapeConfigs: |
        - job_name: kubernetes-pods-tenant
          kubernetes_sd_configs:
            - role: pod
          relabel_configs:
            - source_labels: [__meta_kubernetes_namespace]
              regex: tenant-(.*)
              action: keep
            - source_labels: [__meta_kubernetes_namespace]
              target_label: namespace
            - source_labels: [__meta_kubernetes_pod_name]
              target_label: pod
            - source_labels: [__meta_kubernetes_pod_label_app]
              target_label: app
            - source_labels: [__meta_kubernetes_namespace]
              regex: tenant-(.*)
              replacement: $1
              target_label: tenant
