apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timeguild-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/si3mshady/time-guild-gitops.git'
    targetRevision: HEAD
    path: infra/helm/timeguild
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: timeguild-prod
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: timeguild-prod-secrets
      jsonPointers:
        - /data
  syncPolicy:
    # Disable automated sync in production to require manual approval of git commits
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
