apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: timeguild-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/si3mshady/time-guild-gitops.git'
    targetRevision: HEAD
    path: infra/helm/timeguild
    helm:
      valueFiles:
        - values.yaml
        - values-lab.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: timeguild-staging
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: timeguild-staging-secrets
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
